/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appManagerApiClient

type DeploymentSpec struct {
	State                        string                        `json:"state"`
	UpgradeStrategy              *DeploymentUpgradeStrategy    `json:"upgradeStrategy"`
	RestoreStrategy              *DeploymentRestoreStrategy    `json:"restoreStrategy,omitempty"`
	StartFromSavepoint           *DeploymentStartFromSavepoint `json:"startFromSavepoint,omitempty"`
	DeploymentTargetId           string                        `json:"deploymentTargetId"`
	MaxSavepointCreationAttempts int32                         `json:"maxSavepointCreationAttempts,omitempty"`
	MaxJobCreationAttempts       int32                         `json:"maxJobCreationAttempts,omitempty"`
	Template                     *DeploymentTemplate           `json:"template"`
}
