/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appManagerApiClient

import core "k8s.io/api/core/v1"

type Pods struct {
	Annotations      map[string]string           `json:"annotations,omitempty"`
	NodeSelector     map[string]string           `json:"nodeSelector,omitempty"`
	SecurityContext  *core.SecurityContext       `json:"securityContext,omitempty"`
	Affinity         *core.Affinity              `json:"affinity,omitempty"`
	Tolerations      []core.Toleration           `json:"tolerations,omitempty"`
	VolumeMounts     []VolumeAndMount            `json:"volumeMounts,omitempty"`
	EnvVars          []core.EnvVar               `json:"envVars,omitempty"`
	ImagePullSecrets []core.LocalObjectReference `json:"imagePullSecrets,omitempty"`
}
