/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

type RoleBindingSpec struct {
	Subjects *IterableRoleBindingSubject `json:"subjects"`
	RoleRef *RoleBindingRoleRef `json:"roleRef"`
}
