// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	platform "github.com/fintechstudios/ververica-platform-k8s-operator/pkg/vvp/platform"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// APITokens provides a mock function with given fields:
func (_m *Client) APITokens() platform.APITokensService {
	ret := _m.Called()

	var r0 platform.APITokensService
	if rf, ok := ret.Get(0).(func() platform.APITokensService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(platform.APITokensService)
		}
	}

	return r0
}

// Namespaces provides a mock function with given fields:
func (_m *Client) Namespaces() platform.NamespacesService {
	ret := _m.Called()

	var r0 platform.NamespacesService
	if rf, ok := ret.Get(0).(func() platform.NamespacesService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(platform.NamespacesService)
		}
	}

	return r0
}
