/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package platformapi

type TableColumn struct {
	Expression string                     `json:"expression,omitempty"`
	Meta       *MetadataColumnInformation `json:"meta,omitempty"`
	Name       string                     `json:"name,omitempty"`
	Type_      string                     `json:"type,omitempty"`
}
