/*
 * Ververica Platform API
 *
 * The Ververica Platform APIs, excluding Application Manager.
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package platformapi

import (
	"time"
)

type SqlScript struct {
	CreateTime  time.Time `json:"createTime,omitempty"`
	Description string    `json:"description,omitempty"`
	DisplayName string    `json:"displayName,omitempty"`
	Name        string    `json:"name,omitempty"`
	Script      string    `json:"script,omitempty"`
	UpdateTime  time.Time `json:"updateTime,omitempty"`
}
