/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

type LicenseSpec struct {
	LicenseId  string            `json:"licenseId,omitempty"`
	LicensedTo string            `json:"licensedTo,omitempty"`
	Expires    int64             `json:"expires,omitempty"`
	Params     map[string]string `json:"params,omitempty"`
}
