/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type JobStatus struct {
	State   string   `json:"state,omitempty"`
	Failure *Failure `json:"failure,omitempty"`
}
