/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type Artifact struct {
	Kind               string `json:"kind"`
	JarUri             string `json:"jarUri"`
	MainArgs           string `json:"mainArgs,omitempty"`
	EntryClass         string `json:"entryClass,omitempty"`
	FlinkVersion       string `json:"flinkVersion,omitempty"`
	FlinkImageRegistry string `json:"flinkImageRegistry,omitempty"`
	FlinkImageTag      string `json:"flinkImageTag,omitempty"`
}
