/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type JobSpec struct {
	Artifact *Artifact `json:"artifact,omitempty"`
	Parallelism int32 `json:"parallelism,omitempty"`
	FlinkConfiguration map[string]string `json:"flinkConfiguration,omitempty"`
	Resources map[string]ResourceSpec `json:"resources,omitempty"`
	SavepointLocation string `json:"savepointLocation,omitempty"`
	AllowNonRestoredState bool `json:"allowNonRestoredState,omitempty"`
	NumberOfTaskManagers int32 `json:"numberOfTaskManagers,omitempty"`
	Logging *Logging `json:"logging,omitempty"`
	Kubernetes *KubernetesOptions `json:"kubernetes,omitempty"`
	DeploymentTarget *JobDeploymentTarget `json:"deploymentTarget,omitempty"`
}
