/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type ClusterRoleBindingRoleRef struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}
