/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type RevisionInformation struct {
	CommitShaLong  string `json:"commitShaLong,omitempty"`
	CommitShaShort string `json:"commitShaShort,omitempty"`
	BuildVersion   string `json:"buildVersion,omitempty"`
	BuildTime      string `json:"buildTime,omitempty"`
}
