/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type SavepointMetadata struct {
	Id              string            `json:"id,omitempty"`
	CreatedAt       int64             `json:"createdAt,omitempty"`
	ModifiedAt      int64             `json:"modifiedAt,omitempty"`
	DeploymentId    string            `json:"deploymentId"`
	JobId           string            `json:"jobId,omitempty"`
	Origin          string            `json:"origin,omitempty"`
	Annotations     map[string]string `json:"annotations,omitempty"`
	ResourceVersion int32             `json:"resourceVersion,omitempty"`
	Namespace       string            `json:"namespace,omitempty"`
}
