/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type Pods struct {
	Annotations      map[string]string      `json:"annotations,omitempty"`
	NodeSelector     map[string]string      `json:"nodeSelector,omitempty"`
	SecurityContext  *JsonNode              `json:"securityContext,omitempty"`
	Affinity         *JsonNode              `json:"affinity,omitempty"`
	Tolerations      []JsonNode             `json:"tolerations,omitempty"`
	VolumeMounts     []VolumeAndMount       `json:"volumeMounts,omitempty"`
	EnvVars          []EnvVar               `json:"envVars,omitempty"`
	ImagePullSecrets []LocalObjectReference `json:"imagePullSecrets,omitempty"`
}
