/*
 * AppManager API
 *
 * HTTP REST API to connect to the AppManager
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ververicaplatformapi

type LicenseMetadata struct {
	Id          string            `json:"id,omitempty"`
	CreatedAt   int64             `json:"createdAt,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}
