/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

type Event struct {
	ApiVersion string `json:"apiVersion,omitempty"`
	Kind string `json:"kind,omitempty"`
	Metadata *EventMetadata `json:"metadata,omitempty"`
	Spec *EventSpec `json:"spec,omitempty"`
}
