/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

// Represents a vSphere volume resource.
type V1VsphereVirtualDiskVolumeSource struct {
	// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
	FsType string `json:"fsType,omitempty"`
	// Storage Policy Based Management (SPBM) profile ID associated with the StoragePolicyName.
	StoragePolicyID string `json:"storagePolicyID,omitempty"`
	// Storage Policy Based Management (SPBM) profile name.
	StoragePolicyName string `json:"storagePolicyName,omitempty"`
	// Path that identifies vSphere volume vmdk
	VolumePath string `json:"volumePath"`
}
