/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

// PersistentVolumeClaimTemplate is used to produce PersistentVolumeClaim objects as part of an EphemeralVolumeSource.
type V1PersistentVolumeClaimTemplate struct {
	Metadata *V1ObjectMeta `json:"metadata,omitempty"`
	Spec *V1PersistentVolumeClaimSpec `json:"spec"`
}
