/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

// Handler defines a specific action that should be taken
type V1Handler struct {
	Exec *V1ExecAction `json:"exec,omitempty"`
	HttpGet *V1HttpGetAction `json:"httpGet,omitempty"`
	TcpSocket *V1TcpSocketAction `json:"tcpSocket,omitempty"`
}
