/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

type JobTable struct {
	CatalogName string `json:"catalogName,omitempty"`
	Columns []JobTableColumn `json:"columns,omitempty"`
	DatabaseName string `json:"databaseName,omitempty"`
	Name string `json:"name,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	Temporary bool `json:"temporary,omitempty"`
}
