/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

// SELinuxOptions are the labels to be applied to the container
type V1SeLinuxOptions struct {
	// Level is SELinux level label that applies to the container.
	Level string `json:"level,omitempty"`
	// Role is a SELinux role label that applies to the container.
	Role string `json:"role,omitempty"`
	// Type is a SELinux type label that applies to the container.
	Type_ string `json:"type,omitempty"`
	// User is a SELinux user label that applies to the container.
	User string `json:"user,omitempty"`
}
