/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

type SessionCluster struct {
	ApiVersion string `json:"apiVersion,omitempty"`
	Kind string `json:"kind,omitempty"`
	Metadata *SessionClusterMetadata `json:"metadata,omitempty"`
	Spec *SessionClusterSpec `json:"spec,omitempty"`
	Status *SessionClusterStatus `json:"status,omitempty"`
}
