/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.4.3
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

// SecretKeySelector selects a key of a Secret.
type V1SecretKeySelector struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional bool `json:"optional,omitempty"`
}
