/*
 * Application Manager API
 *
 * Application Manager APIs to control Apache Flink jobs
 *
 * API version: 2.1.0
 * Contact: platform@ververica.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package appmanagerapi

type DeploymentSpec struct {
	DeploymentTargetId           string                     `json:"deploymentTargetId,omitempty"`
	MaxJobCreationAttempts       int32                      `json:"maxJobCreationAttempts,omitempty"`
	MaxSavepointCreationAttempts int32                      `json:"maxSavepointCreationAttempts,omitempty"`
	RestoreStrategy              *DeploymentRestoreStrategy `json:"restoreStrategy,omitempty"`
	State                        string                     `json:"state,omitempty"`
	Template                     *DeploymentTemplate        `json:"template,omitempty"`
	UpgradeStrategy              *DeploymentUpgradeStrategy `json:"upgradeStrategy,omitempty"`
}
